name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86, x64, arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            sudo apt-get update
            sudo apt-get install -y autoconf gcc make
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            choco install make mingw
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            brew install autoconf gcc make
          fi

      - name: Clone Easel repository
        run: |
          git clone https://github.com/TravisWheelerLab/easel
          cd easel
          git checkout BATH
          cd ..

      - name: Run autoconf
        run: autoconf

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BATH-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            src/bathsearch
            src/bathbuild
            src/bathconvert
            src/bathfetch
            src/bathstat
          if-no-files-found: error

  release:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86, x64, arm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        run: |
          mkdir -p ./artifacts/${{ matrix.os }}/${{ matrix.arch }}
          mv ./src/* ./artifacts/${{ matrix.os }}/${{ matrix.arch }}/

      - name: Create Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ github.ref }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/${{ matrix.os }}-${{ matrix.arch }}
          asset_name: BATH-${{ matrix.os }}-${{ matrix.arch }}
          asset_content_type: application/octet-stream
