name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64, arm]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure Git for Windows
        if: matrix.os == 'windows-latest'
        run: |
          git config --global core.autocrlf input

      - name: Set up build environment
        shell: bash
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            sudo apt-get update
            sudo apt-get install -y autoconf gcc make
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            brew install autoconf gcc make
          fi

      - name: Set up MSYS2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain autoconf automake libtool

      - name: Clone Easel repository
        run: |
          git clone https://github.com/TravisWheelerLab/easel
          cd easel
          git checkout BATH
          cd ..

      - name: Run autoconf on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        run: autoconf
        shell: bash

      - name: Run autoconf on Windows
        if: matrix.os == 'windows-latest'
        run: autoconf
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64

      - name: Run configure on Windows
        if: matrix.os == 'windows-latest'
        run: ./configure
        shell: msys2 {0}
        env:
          MSYSTEM: MINGW64

      - name: Run configure on Ubuntu and macOS
        if: matrix.os != 'windows-latest'
        run: ./configure
        shell: bash

      - name: Build
        run: |
          make
          mkdir -p installation/usr/local/bin
          cd src && make install DESTDIR=../installation

      - name: Extract version from github.ref
        id: extract_version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Create tar.gz archive
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            cd installation/usr/local/bin
            zip -r ../../../BATH-${{ steps.extract_version.outputs.version }}.${{ matrix.os }}.${{ matrix.arch }}.zip bathsearch.exe bathbuild.exe bathconvert.exe bathfetch.exe bathstat.exe
          else
            cd installation/usr/local/bin
            tar -czvf ../../../BATH-${{ steps.extract_version.outputs.version }}.${{ matrix.os }}.${{ matrix.arch }}.tar.gz bathsearch bathbuild bathconvert bathfetch bathstat
          fi

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BATH-${{ matrix.os }}-${{ matrix.arch }}
          path: installation/BATH-${{ steps.extract_version.outputs.version }}.${{ matrix.os }}.${{ matrix.arch }}.tar.gz
          if-no-files-found: error

  release:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86, x64, arm]
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: BATH-${{ matrix.os }}-${{ matrix.arch }}
          path: ./artifacts

      - name: List files in artifacts directory
        run: |
          echo "Listing files in ./artifacts:"
          ls -l ./artifacts

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/BATH-${{ matrix.os }}-${{ matrix.arch }}/*
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
